# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 05:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('registered_date', models.DateTimeField(default=datetime.datetime(2017, 7, 4, 5, 52, 32, 134287, tzinfo=utc))),
            ],
        ),
    ]
