# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeville', '0002_auto_20170704_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
