# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeville', '0005_auto_20170704_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone_text',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
